# Site settings
title: Pi Plant monitoring web app
description: This web app allows users to create their own custom plant monitoring webpage.
logo: logo.png
show_downloads: true
# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme