# Site settings
title: Pi Plant monitoring web app
description: "This web app allows users to create their own custom plant monitoring webpage"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
